theme: jekyll-theme-minimal
title: Bernardi SPRL
author:
  name: Raffaele Bernardi
timezone: "Europe/Brussels"
highlighter: rouge
show_downloads: false
logo: /images/ieciab_logo.png
description: Expert comptable certifié.
